<?php

acf_add_local_field_group([
	'key' => 'group_605b6af3e7842',
	'title' => '[Canva BE] - Query (Terms of post)',
	'fields' => [
		[
			'key' => 'field_qk3ekzy2ynn4hvjj',
			'label' => 'Query setup',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		],
		[
			'key' => 'field_ww5dgtkywmpv8pya',
			'label' => 'Post Type Slug',
			'name' => 'post_type_slug',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '50',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => 'post',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_uebdphp45yvpgjfw',
			'label' => 'Taxonomy Slug',
			'name' => 'taxonomy_slug',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '50',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => 'category',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		// [
		// 	'key' => 'field_3xyz6u5igwcnry7c',
		// 	'label' => 'Term Slug',
		// 	'name' => 'term_slug',
		// 	'type' => 'text',
		// 	'instructions' => '',
		// 	'required' => 0,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => [
		// 		'width' => '50',
		// 		'class' => '',
		// 		'id' => '',
		// 	],
		// 	'default_value' => '',
		// 	'placeholder' => 'nike',
		// 	'prepend' => '',
		// 	'append' => '',
		// 	'maxlength' => '',
		// ],
		[
			'key' => 'field_582q9qpn2fbfg8dm',
			'label' => 'Template Name',
			'name' => 'template_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		],
		[
			'key' => 'field_79ir5jfegpmht9b5',
			'label' => 'Posts per Page',
			'name' => 'posts_per_page',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '50',
				'class' => '',
				'id' => '',
			],
			'default_value' => 9,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		],
		[
			'key' => 'field_67n9cz2999im4enk',
			'label' => 'Offset',
			'name' => 'offset',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '50',
				'class' => '',
				'id' => '',
			],
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		],
		[
			'key' => 'field_3abbjxicwx3mcgr7',
			'label' => 'Order',
			'name' => 'order',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '50',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'ASC' => 'ASC',
				'DESC' => 'DESC',
			],
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		],
		[
			'key' => 'field_58ftxu7iixnwafm9',
			'label' => 'Order By',
			'name' => 'orderby',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '50',
				'class' => '',
				'id' => '',
			],
			'choices' => [
				'author' => 'Author',
				'title' => 'Title',
				'date' => 'Date',
				'rand' => 'Random',
				'comment_count' => 'Comment Count',
			],
			'default_value' => 'title',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		], [
			'key' => 'field_akuhpt9vw6gypugg',
			'label' => 'Visibility setup',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '',
				'class' => '',
				'id' => '',
			],
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		],
		[
			'key' => 'field_v78citgrife4uj76',
			'label' => 'Hide',
			'name' => 'hide',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_dha9zycav2wqqnbb',
			'label' => 'Preview',
			'name' => 'show_for_admin',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => [
				[
					[
						'field' => 'field_v78citgrife4uj76',
						'operator' => '==',
						'value' => '1',
					],
				],
			],
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_pv4qxdad9pyta9ic',
			'label' => 'Facetwp',
			'name' => 'facetwp_mode',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_ie9up3ivrw5tw5qd',
			'label' => 'Swiper',
			'name' => 'swiper_mode',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_nrzy2av99ig268zx',
			'label' => 'Coming',
			'name' => 'coming',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_zt8qgrpmqvbr5jhz',
			'label' => 'During',
			'name' => 'during',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_6i282qubx55cmqyu',
			'label' => 'Past',
			'name' => 'past',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
		[
			'key' => 'field_lljcbh9g4wdf0bc5',
			'label' => 'Results',
			'name' => 'results',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => [
				'width' => '33',
				'class' => '',
				'id' => '',
			],
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'On',
			'ui_off_text' => 'Off',
		],
	],
	'location' => [
		[
			[
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/posts-per-terms-of-post-selector',
			],
		],
	],
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'recaptcha' => 0,
]);
