###
# PrimoGroup Rest API #
GET https://www.primoup.it/api/v1/login?email=websites@primoup.it&password=wJnhstkX9T8V HTTP/1.1
content-type: application/json

###
# PrimoGroup Rest API - Clinics#
GET https://www.primoup.it/api/v1/clinics?api_token=euaB40Rw31oqMUMrhoZtkSycXIGacd6JU22voV8UULTvKA5GQxDp62VYDATK HTTP/1.1
content-type: application/json

###
# PrimoGroup Rest API - OpenDays#
GET https://www.primoup.it/api/v1/open_days?page=2&api_token=euaB40Rw31oqMUMrhoZtkSycXIGacd6JU22voV8UULTvKA5GQxDp62VYDATK HTTP/1.1
content-type: application/json

###
# PrimoGroup Rest API - OpenDay Singola#
GET https://www.primoup.it/api/v1/open_days/13?api_token=euaB40Rw31oqMUMrhoZtkSycXIGacd6JU22voV8UULTvKA5GQxDp62VYDATK HTTP/1.1
content-type: application/json

###
# PrimoGroup Rest API - OpenDays Type#
GET https://www.primoup.it/api/v1/open_day_types?api_token=euaB40Rw31oqMUMrhoZtkSycXIGacd6JU22voV8UULTvKA5GQxDp62VYDATK HTTP/1.1
content-type: application/json

###
# PrimoGroup Rest API - OpenDays Province#
GET https://www.primoup.it/api/v1/open_days_provinces?api_token=euaB40Rw31oqMUMrhoZtkSycXIGacd6JU22voV8UULTvKA5GQxDp62VYDATK HTTP/1.1
content-type: application/json

###
# PrimoGroup Zucchetti HR #
GET https://test-primogroup.intervieweb.it/annunci.php?lang=it&d=centridentisticiprimo.it&k=94a5e33a274a19b813e3d307345f591f&CodP=1&format=json_en&utype=0 HTTP/1.1
content-type: application/json

